#ifndef PPC_H
#define PPC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

struct ppc_bus {
    uint8_t (*read8)(void*, uint32_t addr);
    uint16_t (*read16)(void*, uint32_t addr);
    uint32_t (*read32)(void*, uint32_t addr);
    uint64_t (*read64)(void*, uint32_t addr);
    void (*write8)(void*, uint32_t addr, uint8_t data);
    void (*write16)(void*, uint32_t addr, uint16_t data);
    void (*write32)(void*, uint32_t addr, uint32_t data);
    void (*write64)(void*, uint32_t addr, uint64_t data);
    void* udata;
};

struct ppc_state {
    struct ppc_bus bus;

    union {
        uint32_t cr;

        struct {
            unsigned int cr0 : 4;
            unsigned int cr1 : 4;
            unsigned int cr2 : 4;
            unsigned int cr3 : 4;
            unsigned int cr4 : 4;
            unsigned int cr5 : 4;
            unsigned int cr6 : 4;
            unsigned int cr7 : 4;
        };
    };

    uint64_t lr;
    uint64_t ctr;
    uint64_t r[32];
    uint64_t xer;
    uint32_t pc;
    uint32_t opcode;
};

struct ppc_state* ppc_create(struct ppc_bus bus);
void ppc_init(struct ppc_state* cpu, struct ppc_bus bus);
uint8_t ppc_read8(struct ppc_state* cpu, uint32_t addr);
uint16_t ppc_read16(struct ppc_state* cpu, uint32_t addr);
uint32_t ppc_read32(struct ppc_state* cpu, uint32_t addr);
uint64_t ppc_read64(struct ppc_state* cpu, uint32_t addr);
void ppc_write8(struct ppc_state* cpu, uint32_t addr, uint8_t data);
void ppc_write16(struct ppc_state* cpu, uint32_t addr, uint16_t data);
void ppc_write32(struct ppc_state* cpu, uint32_t addr, uint32_t data);
void ppc_write64(struct ppc_state* cpu, uint32_t addr, uint64_t data);
int ppc_execute(struct ppc_state* cpu);
void ppc_destroy(struct ppc_state* cpu);

void ppc_adde(struct ppc_state* cpu);
void ppc_add(struct ppc_state* cpu);
void ppc_and(struct ppc_state* cpu);
void ppc_addc(struct ppc_state* cpu);
void ppc_andc(struct ppc_state* cpu);
void ppc_addme(struct ppc_state* cpu);
void ppc_addis(struct ppc_state* cpu);
void ppc_addi(struct ppc_state* cpu);
void ppc_addic_u(struct ppc_state* cpu);
void ppc_addic(struct ppc_state* cpu);
void ppc_andi_u(struct ppc_state* cpu);
void ppc_addze(struct ppc_state* cpu);
void ppc_andis_u(struct ppc_state* cpu);
void ppc_bc(struct ppc_state* cpu);
void ppc_b(struct ppc_state* cpu);
void ppc_bclr(struct ppc_state* cpu);
void ppc_bcctr(struct ppc_state* cpu);
void ppc_cmp(struct ppc_state* cpu);
void ppc_cntlzw(struct ppc_state* cpu);
void ppc_cmpl(struct ppc_state* cpu);
void ppc_crxor(struct ppc_state* cpu);
void ppc_cror(struct ppc_state* cpu);
void ppc_crorc(struct ppc_state* cpu);
void ppc_creqv(struct ppc_state* cpu);
void ppc_crand(struct ppc_state* cpu);
void ppc_crnand(struct ppc_state* cpu);
void ppc_crandc(struct ppc_state* cpu);
void ppc_crnor(struct ppc_state* cpu);
void ppc_cntlzd(struct ppc_state* cpu);
void ppc_cmpi(struct ppc_state* cpu);
void ppc_cmpli(struct ppc_state* cpu);
void ppc_dcbst(struct ppc_state* cpu);
void ppc_divd(struct ppc_state* cpu);
void ppc_dcbtst(struct ppc_state* cpu);
void ppc_dcbt(struct ppc_state* cpu);
void ppc_dcbf(struct ppc_state* cpu);
void ppc_divdu(struct ppc_state* cpu);
void ppc_divwu(struct ppc_state* cpu);
void ppc_divw(struct ppc_state* cpu);
void ppc_dcbz(struct ppc_state* cpu);
void ppc_ecowx(struct ppc_state* cpu);
void ppc_eieio(struct ppc_state* cpu);
void ppc_extsh(struct ppc_state* cpu);
void ppc_extsw(struct ppc_state* cpu);
void ppc_extsb(struct ppc_state* cpu);
void ppc_eqv(struct ppc_state* cpu);
void ppc_eciwx(struct ppc_state* cpu);
void ppc_frsqrte(struct ppc_state* cpu);
void ppc_fadds(struct ppc_state* cpu);
void ppc_fsubs(struct ppc_state* cpu);
void ppc_fdivs(struct ppc_state* cpu);
void ppc_fre(struct ppc_state* cpu);
void ppc_fmul(struct ppc_state* cpu);
void ppc_fsqrts(struct ppc_state* cpu);
void ppc_fmsub(struct ppc_state* cpu);
void ppc_fmadd(struct ppc_state* cpu);
void ppc_fnmsub(struct ppc_state* cpu);
void ppc_fnmadd(struct ppc_state* cpu);
void ppc_fcmpo(struct ppc_state* cpu);
void ppc_fcfid(struct ppc_state* cpu);
void ppc_fsel(struct ppc_state* cpu);
void ppc_fnmadds(struct ppc_state* cpu);
void ppc_fres(struct ppc_state* cpu);
void ppc_fmuls(struct ppc_state* cpu);
void ppc_frsqrtes(struct ppc_state* cpu);
void ppc_fmsubs(struct ppc_state* cpu);
void ppc_fsqrt(struct ppc_state* cpu);
void ppc_fadd(struct ppc_state* cpu);
void ppc_fsub(struct ppc_state* cpu);
void ppc_fdiv(struct ppc_state* cpu);
void ppc_fctiwz(struct ppc_state* cpu);
void ppc_fmadds(struct ppc_state* cpu);
void ppc_fctiw(struct ppc_state* cpu);
void ppc_frsp(struct ppc_state* cpu);
void ppc_fnmsubs(struct ppc_state* cpu);
void ppc_fcmpu(struct ppc_state* cpu);
void ppc_fneg(struct ppc_state* cpu);
void ppc_fctid(struct ppc_state* cpu);
void ppc_fmr(struct ppc_state* cpu);
void ppc_fctidz(struct ppc_state* cpu);
void ppc_fabs(struct ppc_state* cpu);
void ppc_fnabs(struct ppc_state* cpu);
void ppc_hrfid(struct ppc_state* cpu);
void ppc_isync(struct ppc_state* cpu);
void ppc_icbi(struct ppc_state* cpu);
void ppc_ldx(struct ppc_state* cpu);
void ppc_lswx(struct ppc_state* cpu);
void ppc_lhzux(struct ppc_state* cpu);
void ppc_lwarx(struct ppc_state* cpu);
void ppc_lwax(struct ppc_state* cpu);
void ppc_lhax(struct ppc_state* cpu);
void ppc_ld(struct ppc_state* cpu);
void ppc_ldu(struct ppc_state* cpu);
void ppc_lwaux(struct ppc_state* cpu);
void ppc_lhaux(struct ppc_state* cpu);
void ppc_lwa(struct ppc_state* cpu);
void ppc_lhbrx(struct ppc_state* cpu);
void ppc_lfdux(struct ppc_state* cpu);
void ppc_lfdx(struct ppc_state* cpu);
void ppc_lswi(struct ppc_state* cpu);
void ppc_lfsux(struct ppc_state* cpu);
void ppc_lfsx(struct ppc_state* cpu);
void ppc_lwbrx(struct ppc_state* cpu);
void ppc_lhzx(struct ppc_state* cpu);
void ppc_lmw(struct ppc_state* cpu);
void ppc_lfs(struct ppc_state* cpu);
void ppc_lhau(struct ppc_state* cpu);
void ppc_lha(struct ppc_state* cpu);
void ppc_lhzu(struct ppc_state* cpu);
void ppc_lhz(struct ppc_state* cpu);
void ppc_lbzux(struct ppc_state* cpu);
void ppc_lfsu(struct ppc_state* cpu);
void ppc_lbzx(struct ppc_state* cpu);
void ppc_ldarx(struct ppc_state* cpu);
void ppc_lfd(struct ppc_state* cpu);
void ppc_lfdu(struct ppc_state* cpu);
void ppc_lbzu(struct ppc_state* cpu);
void ppc_lbz(struct ppc_state* cpu);
void ppc_lwzu(struct ppc_state* cpu);
void ppc_lwz(struct ppc_state* cpu);
void ppc_lwzux(struct ppc_state* cpu);
void ppc_ldux(struct ppc_state* cpu);
void ppc_lwzx(struct ppc_state* cpu);
void ppc_mfsrin(struct ppc_state* cpu);
void ppc_mulli(struct ppc_state* cpu);
void ppc_mtfsf(struct ppc_state* cpu);
void ppc_mfsr(struct ppc_state* cpu);
void ppc_mcrf(struct ppc_state* cpu);
void ppc_mffs(struct ppc_state* cpu);
void ppc_mtcrf(struct ppc_state* cpu);
void ppc_mulld(struct ppc_state* cpu);
void ppc_mfcr(struct ppc_state* cpu);
void ppc_mftb(struct ppc_state* cpu);
void ppc_mfocrf(struct ppc_state* cpu);
void ppc_mcrxr(struct ppc_state* cpu);
void ppc_mtfsfi(struct ppc_state* cpu);
void ppc_mtfsb0(struct ppc_state* cpu);
void ppc_mtsrin(struct ppc_state* cpu);
void ppc_mullw(struct ppc_state* cpu);
void ppc_mcrfs(struct ppc_state* cpu);
void ppc_mfspr(struct ppc_state* cpu);
void ppc_mulhd(struct ppc_state* cpu);
void ppc_mulhw(struct ppc_state* cpu);
void ppc_mfmsr(struct ppc_state* cpu);
void ppc_mtsr(struct ppc_state* cpu);
void ppc_mtmsrd(struct ppc_state* cpu);
void ppc_mtfsb1(struct ppc_state* cpu);
void ppc_mtmsr(struct ppc_state* cpu);
void ppc_mtocrf(struct ppc_state* cpu);
void ppc_mulhwu(struct ppc_state* cpu);
void ppc_mulhdu(struct ppc_state* cpu);
void ppc_mtspr(struct ppc_state* cpu);
void ppc_nor(struct ppc_state* cpu);
void ppc_neg(struct ppc_state* cpu);
void ppc_nand(struct ppc_state* cpu);
void ppc_orc(struct ppc_state* cpu);
void ppc_ori(struct ppc_state* cpu);
void ppc_oris(struct ppc_state* cpu);
void ppc_or(struct ppc_state* cpu);
void ppc_popcntb(struct ppc_state* cpu);
void ppc_rfid(struct ppc_state* cpu);
void ppc_rldicl(struct ppc_state* cpu);
void ppc_rldicr(struct ppc_state* cpu);
void ppc_rldic(struct ppc_state* cpu);
void ppc_rldimi(struct ppc_state* cpu);
void ppc_rldcl(struct ppc_state* cpu);
void ppc_rldcr(struct ppc_state* cpu);
void ppc_rlwnm(struct ppc_state* cpu);
void ppc_rlwinm(struct ppc_state* cpu);
void ppc_rlwimi(struct ppc_state* cpu);
void ppc_sradi(struct ppc_state* cpu);
void ppc_stfs(struct ppc_state* cpu);
void ppc_stfsu(struct ppc_state* cpu);
void ppc_stfd(struct ppc_state* cpu);
void ppc_stfdu(struct ppc_state* cpu);
void ppc_std(struct ppc_state* cpu);
void ppc_stmw(struct ppc_state* cpu);
void ppc_stdu(struct ppc_state* cpu);
void ppc_stdcx_u(struct ppc_state* cpu);
void ppc_slbia(struct ppc_state* cpu);
void ppc_sthux(struct ppc_state* cpu);
void ppc_slbie(struct ppc_state* cpu);
void ppc_subfic(struct ppc_state* cpu);
void ppc_sthx(struct ppc_state* cpu);
void ppc_slbmte(struct ppc_state* cpu);
void ppc_sc(struct ppc_state* cpu);
void ppc_subfc(struct ppc_state* cpu);
void ppc_stbux(struct ppc_state* cpu);
void ppc_subfme(struct ppc_state* cpu);
void ppc_stbx(struct ppc_state* cpu);
void ppc_srw(struct ppc_state* cpu);
void ppc_subfze(struct ppc_state* cpu);
void ppc_stwux(struct ppc_state* cpu);
void ppc_stdux(struct ppc_state* cpu);
void ppc_stwx(struct ppc_state* cpu);
void ppc_stwcx_u(struct ppc_state* cpu);
void ppc_stdx(struct ppc_state* cpu);
void ppc_subfe(struct ppc_state* cpu);
void ppc_slw(struct ppc_state* cpu);
void ppc_subf(struct ppc_state* cpu);
void ppc_sld(struct ppc_state* cpu);
void ppc_sraw(struct ppc_state* cpu);
void ppc_sth(struct ppc_state* cpu);
void ppc_stbu(struct ppc_state* cpu);
void ppc_stb(struct ppc_state* cpu);
void ppc_stwu(struct ppc_state* cpu);
void ppc_stw(struct ppc_state* cpu);
void ppc_stfiwx(struct ppc_state* cpu);
void ppc_sthbrx(struct ppc_state* cpu);
void ppc_slbmfee(struct ppc_state* cpu);
void ppc_slbmfev(struct ppc_state* cpu);
void ppc_srawi(struct ppc_state* cpu);
void ppc_srad(struct ppc_state* cpu);
void ppc_stfdux(struct ppc_state* cpu);
void ppc_stfdx(struct ppc_state* cpu);
void ppc_stswi(struct ppc_state* cpu);
void ppc_stfsux(struct ppc_state* cpu);
void ppc_stfsx(struct ppc_state* cpu);
void ppc_stwbrx(struct ppc_state* cpu);
void ppc_stswx(struct ppc_state* cpu);
void ppc_sync(struct ppc_state* cpu);
void ppc_sthu(struct ppc_state* cpu);
void ppc_srd(struct ppc_state* cpu);
void ppc_twi(struct ppc_state* cpu);
void ppc_tw(struct ppc_state* cpu);
void ppc_td(struct ppc_state* cpu);
void ppc_tlbie(struct ppc_state* cpu);
void ppc_tlbia(struct ppc_state* cpu);
void ppc_tdi(struct ppc_state* cpu);
void ppc_tlbsync(struct ppc_state* cpu);
void ppc_xor(struct ppc_state* cpu);
void ppc_xoris(struct ppc_state* cpu);
void ppc_xori(struct ppc_state* cpu);

#ifdef __cplusplus
}
#endif

#endif